feat: implement notification filtering
savannahghi/pro_health_360 pull request #813
Opened 2022-07-22 13:23 UTC by byronkimani

- implement notification filtering

Signed-off-by: Byron Kimani <byronkimani@Byrons-MacBook-Pro.local>

2022-07-26 12:01 UTC, EugeneDevv approved these changes

2022-07-27 06:09 UTC, abiudrn requested changes

2022-07-27 06:09 UTC, abiudrn commented on lib/application/redux/actions/notifications/fetch_notification_filters_action.dart
> +      NotificationFilter(name: readText),
Do we need to show users notifications they have read? This might be inefficient because there could be a long list of read notifications

2022-07-27 08:28 UTC, abiudrn approved these changes

2022-07-27 08:28 UTC, merged