chore: change android app name
savannahghi/pro_health_360 pull request #836
Opened 2022-08-25 13:11 UTC by byronkimani

- change android app name

Signed-off-by: Byron Kimani <byronkimani@Byrons-MacBook-Pro.local>

2022-08-25 13:47 UTC, EugeneDevv approved these changes

2022-08-26 06:49 UTC, abiudrn requested changes

2022-08-26 06:49 UTC, abiudrn commented on ios/fastlane/Fastfile
> +APP_IDENTIFIER = "com.mycarehub.UONAfyaApp360"
Revert this. Deployment to iOS won't work

2022-08-26 09:30 UTC, abiudrn approved these changes

2022-08-26 09:30 UTC, merged